
spring:
  application:
    name: ribbon-consumer
  mvc:
    static-path-pattern: /static/**
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456


server:
  port: 81

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka/
      #defaultZone: http://47.112.20.178:7001/eureka,http://47.112.20.178:7002/eureka

feign:
  hystrix:
    enabled: true

management:
  endpoint:
    health:
      show-details: always