server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://eureka7001:7001/eureka/

#spring:
#  application:
#    name: eureka