server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001
  client:
    serviceUrl:
      defaultZone: http://eureka7002:7002/eureka/
    register-with-eureka: false
    fetch-registry: false
#spring:
#  application:
#    name: eureka